package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/database-playground/backend-v2/ent"
	"github.com/database-playground/backend-v2/graph/model"
	"github.com/database-playground/backend-v2/internal/sqlrunner"
	"github.com/samber/lo"
)

// Structure is the resolver for the structure field.
func (r *databaseResolver) Structure(ctx context.Context, obj *ent.Database) (*model.DatabaseStructure, error) {
	structure, err := r.sqlrunner.GetDatabaseStructure(ctx, obj.Schema)
	if err != nil {
		return nil, err
	}

	return &model.DatabaseStructure{
		Tables: lo.Map(structure.Tables, func(table sqlrunner.DatabaseTable, _ int) *model.DatabaseTable {
			return &model.DatabaseTable{
				Name:    table.Name,
				Columns: table.Columns,
			}
		}),
	}, nil
}
