package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/database-playground/backend-v2/graph/model"
)

// Ranking is the resolver for the ranking field.
func (r *queryResolver) Ranking(ctx context.Context, first *int, after *entgql.Cursor[int], filter model.RankingFilter) (*model.RankingConnection, error) {
	return r.rankingService.GetRanking(ctx, first, after, filter)
}
