package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"strconv"

	"github.com/database-playground/backend-v2/ent"
	"github.com/database-playground/backend-v2/ent/user"
	"github.com/database-playground/backend-v2/graph/defs"
	"github.com/database-playground/backend-v2/internal/auth"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	user, err := r.ent.User.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input ent.UpdateUserInput) (*ent.User, error) {
	user, err := r.ent.User.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, defs.ErrNotFound
		}
		return nil, err
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (bool, error) {
	err := r.ent.User.DeleteOneID(id).Exec(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return false, defs.ErrNotFound
		}
		return false, err
	}

	return true, nil
}

// CreateScopeSet is the resolver for the createScopeSet field.
func (r *mutationResolver) CreateScopeSet(ctx context.Context, input ent.CreateScopeSetInput) (*ent.ScopeSet, error) {
	scopeSet, err := r.ent.ScopeSet.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return scopeSet, nil
}

// UpdateScopeSet is the resolver for the updateScopeSet field.
func (r *mutationResolver) UpdateScopeSet(ctx context.Context, id int, input ent.UpdateScopeSetInput) (*ent.ScopeSet, error) {
	scopeSet, err := r.ent.ScopeSet.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, defs.ErrNotFound
		}
		return nil, err
	}

	return scopeSet, nil
}

// DeleteScopeSet is the resolver for the deleteScopeSet field.
func (r *mutationResolver) DeleteScopeSet(ctx context.Context, id int) (bool, error) {
	err := r.ent.ScopeSet.DeleteOneID(id).Exec(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return false, defs.ErrNotFound
		}
		return false, err
	}

	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input ent.CreateGroupInput) (*ent.Group, error) {
	group, err := r.ent.Group.Create().SetInput(input).Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, defs.ErrNotFound
		}
		return nil, err
	}

	return group, nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id int, input ent.UpdateGroupInput) (*ent.Group, error) {
	group, err := r.ent.Group.UpdateOneID(id).SetInput(input).Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, defs.ErrNotFound
		}
		return nil, err
	}

	return group, nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id int) (bool, error) {
	err := r.ent.Group.DeleteOneID(id).Exec(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return false, defs.ErrNotFound
		}
		return false, err
	}

	return true, nil
}

// ImpersonateUser is the resolver for the impersonateUser field.
func (r *mutationResolver) ImpersonateUser(ctx context.Context, userID int) (string, error) {
	// Get the user information.
	user, err := r.ent.User.Query().Where(user.ID(userID)).Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return "", defs.ErrNotFound
		}

		return "", err
	}

	token, err := r.auth.Create(ctx, auth.TokenInfo{
		UserID:    user.ID,
		UserEmail: user.Email,
		Scopes:    []string{"*"},
		Meta: map[string]string{
			"impersonated_by": strconv.Itoa(userID),
		},
	})
	if err != nil {
		return "", err
	}

	return token, nil
}

// LogoutAll is the resolver for the logoutAll field.
func (r *mutationResolver) LogoutAll(ctx context.Context) (bool, error) {
	user, ok := auth.GetUser(ctx)
	if !ok {
		// this should never happen since we have set proper scope
		return false, defs.ErrUnauthorized
	}

	err := r.auth.DeleteByUser(ctx, user.UserID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteMe is the resolver for the deleteMe field.
func (r *mutationResolver) DeleteMe(ctx context.Context) (bool, error) {
	user, ok := auth.GetUser(ctx)
	if !ok {
		return false, defs.ErrUnauthorized
	}

	err := r.ent.User.DeleteOneID(user.UserID).Exec(ctx)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.User, error) {
	tokenInfo, ok := auth.GetUser(ctx)
	if !ok {
		return nil, defs.ErrUnauthorized
	}

	return r.ent.User.Query().Where(user.ID(tokenInfo.UserID)).Only(ctx)
}

// ImpersonatedBy is the resolver for the impersonatedBy field.
func (r *userResolver) ImpersonatedBy(ctx context.Context, obj *ent.User) (*ent.User, error) {
	tokenInfo, ok := auth.GetUser(ctx)
	if !ok {
		return nil, defs.ErrUnauthorized
	}

	if tokenInfo.Meta["impersonated_by"] == "" {
		return nil, nil
	}

	impersonatedBy, err := strconv.Atoi(tokenInfo.Meta["impersonated_by"])
	if err != nil {
		return nil, err
	}

	user, err := r.ent.User.Query().Where(user.ID(impersonatedBy)).Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}

	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
