// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Filter for scope sets.
//
// The filters are mutually exclusive, only one of them can be provided.
type ScopeSetFilter struct {
	// The ID of the scope set.
	ID *int `json:"id,omitempty"`
	// The slug of the scope set.
	Slug *string `json:"slug,omitempty"`
}

type SubmitAnswerInput struct {
	QuestionID int    `json:"questionID"`
	Answer     string `json:"answer"`
}
