// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/cheatrecord"
	"github.com/database-playground/backend-v2/ent/user"
)

// CheatRecordCreate is the builder for creating a CheatRecord entity.
type CheatRecordCreate struct {
	config
	mutation *CheatRecordMutation
	hooks    []Hook
}

// SetReason sets the "reason" field.
func (_c *CheatRecordCreate) SetReason(v string) *CheatRecordCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetResolvedReason sets the "resolved_reason" field.
func (_c *CheatRecordCreate) SetResolvedReason(v string) *CheatRecordCreate {
	_c.mutation.SetResolvedReason(v)
	return _c
}

// SetNillableResolvedReason sets the "resolved_reason" field if the given value is not nil.
func (_c *CheatRecordCreate) SetNillableResolvedReason(v *string) *CheatRecordCreate {
	if v != nil {
		_c.SetResolvedReason(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *CheatRecordCreate) SetResolvedAt(v time.Time) *CheatRecordCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *CheatRecordCreate) SetNillableResolvedAt(v *time.Time) *CheatRecordCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetCheatedAt sets the "cheated_at" field.
func (_c *CheatRecordCreate) SetCheatedAt(v time.Time) *CheatRecordCreate {
	_c.mutation.SetCheatedAt(v)
	return _c
}

// SetNillableCheatedAt sets the "cheated_at" field if the given value is not nil.
func (_c *CheatRecordCreate) SetNillableCheatedAt(v *time.Time) *CheatRecordCreate {
	if v != nil {
		_c.SetCheatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *CheatRecordCreate) SetUserID(id int) *CheatRecordCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CheatRecordCreate) SetUser(v *User) *CheatRecordCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CheatRecordMutation object of the builder.
func (_c *CheatRecordCreate) Mutation() *CheatRecordMutation {
	return _c.mutation
}

// Save creates the CheatRecord in the database.
func (_c *CheatRecordCreate) Save(ctx context.Context) (*CheatRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheatRecordCreate) SaveX(ctx context.Context) *CheatRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheatRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheatRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheatRecordCreate) defaults() {
	if _, ok := _c.mutation.CheatedAt(); !ok {
		v := cheatrecord.DefaultCheatedAt()
		_c.mutation.SetCheatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheatRecordCreate) check() error {
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "CheatRecord.reason"`)}
	}
	if _, ok := _c.mutation.CheatedAt(); !ok {
		return &ValidationError{Name: "cheated_at", err: errors.New(`ent: missing required field "CheatRecord.cheated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CheatRecord.user"`)}
	}
	return nil
}

func (_c *CheatRecordCreate) sqlSave(ctx context.Context) (*CheatRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheatRecordCreate) createSpec() (*CheatRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CheatRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cheatrecord.Table, sqlgraph.NewFieldSpec(cheatrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(cheatrecord.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.ResolvedReason(); ok {
		_spec.SetField(cheatrecord.FieldResolvedReason, field.TypeString, value)
		_node.ResolvedReason = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(cheatrecord.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = value
	}
	if value, ok := _c.mutation.CheatedAt(); ok {
		_spec.SetField(cheatrecord.FieldCheatedAt, field.TypeTime, value)
		_node.CheatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cheatrecord.UserTable,
			Columns: []string{cheatrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_cheat_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheatRecordCreateBulk is the builder for creating many CheatRecord entities in bulk.
type CheatRecordCreateBulk struct {
	config
	err      error
	builders []*CheatRecordCreate
}

// Save creates the CheatRecord entities in the database.
func (_c *CheatRecordCreateBulk) Save(ctx context.Context) ([]*CheatRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheatRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheatRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheatRecordCreateBulk) SaveX(ctx context.Context) []*CheatRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheatRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheatRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
