// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/database-playground/backend-v2/ent/cheatrecord"
	"github.com/database-playground/backend-v2/ent/user"
)

// CheatRecord is the model entity for the CheatRecord schema.
type CheatRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// ResolvedReason holds the value of the "resolved_reason" field.
	ResolvedReason string `json:"resolved_reason,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt time.Time `json:"resolved_at,omitempty"`
	// CheatedAt holds the value of the "cheated_at" field.
	CheatedAt time.Time `json:"cheated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheatRecordQuery when eager-loading is set.
	Edges              CheatRecordEdges `json:"edges"`
	user_cheat_records *int
	selectValues       sql.SelectValues
}

// CheatRecordEdges holds the relations/edges for other nodes in the graph.
type CheatRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheatRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheatRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cheatrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case cheatrecord.FieldReason, cheatrecord.FieldResolvedReason:
			values[i] = new(sql.NullString)
		case cheatrecord.FieldResolvedAt, cheatrecord.FieldCheatedAt:
			values[i] = new(sql.NullTime)
		case cheatrecord.ForeignKeys[0]: // user_cheat_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheatRecord fields.
func (_m *CheatRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cheatrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cheatrecord.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case cheatrecord.FieldResolvedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_reason", values[i])
			} else if value.Valid {
				_m.ResolvedReason = value.String
			}
		case cheatrecord.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = value.Time
			}
		case cheatrecord.FieldCheatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cheated_at", values[i])
			} else if value.Valid {
				_m.CheatedAt = value.Time
			}
		case cheatrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_cheat_records", value)
			} else if value.Valid {
				_m.user_cheat_records = new(int)
				*_m.user_cheat_records = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheatRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheatRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CheatRecord entity.
func (_m *CheatRecord) QueryUser() *UserQuery {
	return NewCheatRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CheatRecord.
// Note that you need to call CheatRecord.Unwrap() before calling this method if this CheatRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheatRecord) Update() *CheatRecordUpdateOne {
	return NewCheatRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheatRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheatRecord) Unwrap() *CheatRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheatRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheatRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheatRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("resolved_reason=")
	builder.WriteString(_m.ResolvedReason)
	builder.WriteString(", ")
	builder.WriteString("resolved_at=")
	builder.WriteString(_m.ResolvedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cheated_at=")
	builder.WriteString(_m.CheatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheatRecords is a parsable slice of CheatRecord.
type CheatRecords []*CheatRecord
