// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (gr *Group) ScopeSet(ctx context.Context) (result []*ScopeSet, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = gr.NamedScopeSet(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = gr.Edges.ScopeSetOrErr()
	}
	if IsNotLoaded(err) {
		result, err = gr.QueryScopeSet().All(ctx)
	}
	return result, err
}

func (u *User) Group(ctx context.Context) (result []*Group, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedGroup(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.GroupOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryGroup().All(ctx)
	}
	return result, err
}
