// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/points"
	"github.com/database-playground/backend-v2/ent/predicate"
	"github.com/database-playground/backend-v2/ent/user"
)

// PointsUpdate is the builder for updating Points entities.
type PointsUpdate struct {
	config
	hooks    []Hook
	mutation *PointsMutation
}

// Where appends a list predicates to the PointsUpdate builder.
func (_u *PointsUpdate) Where(ps ...predicate.Points) *PointsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PointsUpdate) SetCreatedAt(v time.Time) *PointsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PointsUpdate) SetNillableCreatedAt(v *time.Time) *PointsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PointsUpdate) SetUpdatedAt(v time.Time) *PointsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PointsUpdate) SetDeletedAt(v time.Time) *PointsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PointsUpdate) SetNillableDeletedAt(v *time.Time) *PointsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PointsUpdate) ClearDeletedAt() *PointsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPoints sets the "points" field.
func (_u *PointsUpdate) SetPoints(v int) *PointsUpdate {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointsUpdate) SetNillablePoints(v *int) *PointsUpdate {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointsUpdate) AddPoints(v int) *PointsUpdate {
	_u.mutation.AddPoints(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *PointsUpdate) SetDescription(v string) *PointsUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PointsUpdate) SetNillableDescription(v *string) *PointsUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PointsUpdate) ClearDescription() *PointsUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PointsUpdate) SetUserID(id int) *PointsUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PointsUpdate) SetUser(v *User) *PointsUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PointsMutation object of the builder.
func (_u *PointsUpdate) Mutation() *PointsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PointsUpdate) ClearUser() *PointsUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PointsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PointsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PointsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if points.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized points.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := points.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointsUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Points.user"`)
	}
	return nil
}

func (_u *PointsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(points.Table, points.Columns, sqlgraph.NewFieldSpec(points.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(points.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(points.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(points.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(points.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(points.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(points.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(points.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(points.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   points.UserTable,
			Columns: []string{points.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   points.UserTable,
			Columns: []string{points.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{points.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PointsUpdateOne is the builder for updating a single Points entity.
type PointsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PointsMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *PointsUpdateOne) SetCreatedAt(v time.Time) *PointsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PointsUpdateOne) SetNillableCreatedAt(v *time.Time) *PointsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PointsUpdateOne) SetUpdatedAt(v time.Time) *PointsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PointsUpdateOne) SetDeletedAt(v time.Time) *PointsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PointsUpdateOne) SetNillableDeletedAt(v *time.Time) *PointsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PointsUpdateOne) ClearDeletedAt() *PointsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPoints sets the "points" field.
func (_u *PointsUpdateOne) SetPoints(v int) *PointsUpdateOne {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointsUpdateOne) SetNillablePoints(v *int) *PointsUpdateOne {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointsUpdateOne) AddPoints(v int) *PointsUpdateOne {
	_u.mutation.AddPoints(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *PointsUpdateOne) SetDescription(v string) *PointsUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PointsUpdateOne) SetNillableDescription(v *string) *PointsUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PointsUpdateOne) ClearDescription() *PointsUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PointsUpdateOne) SetUserID(id int) *PointsUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PointsUpdateOne) SetUser(v *User) *PointsUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PointsMutation object of the builder.
func (_u *PointsUpdateOne) Mutation() *PointsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PointsUpdateOne) ClearUser() *PointsUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PointsUpdate builder.
func (_u *PointsUpdateOne) Where(ps ...predicate.Points) *PointsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PointsUpdateOne) Select(field string, fields ...string) *PointsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Points entity.
func (_u *PointsUpdateOne) Save(ctx context.Context) (*Points, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointsUpdateOne) SaveX(ctx context.Context) *Points {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PointsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PointsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if points.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized points.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := points.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointsUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Points.user"`)
	}
	return nil
}

func (_u *PointsUpdateOne) sqlSave(ctx context.Context) (_node *Points, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(points.Table, points.Columns, sqlgraph.NewFieldSpec(points.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Points.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, points.FieldID)
		for _, f := range fields {
			if !points.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != points.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(points.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(points.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(points.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(points.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(points.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(points.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(points.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(points.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   points.UserTable,
			Columns: []string{points.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   points.UserTable,
			Columns: []string{points.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Points{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{points.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
