// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/points"
	"github.com/database-playground/backend-v2/ent/user"
)

// PointsCreate is the builder for creating a Points entity.
type PointsCreate struct {
	config
	mutation *PointsMutation
	hooks    []Hook
}

// SetPoints sets the "points" field.
func (_c *PointsCreate) SetPoints(v int) *PointsCreate {
	_c.mutation.SetPoints(v)
	return _c
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_c *PointsCreate) SetNillablePoints(v *int) *PointsCreate {
	if v != nil {
		_c.SetPoints(*v)
	}
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *PointsCreate) SetGrantedAt(v time.Time) *PointsCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *PointsCreate) SetNillableGrantedAt(v *time.Time) *PointsCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PointsCreate) SetDescription(v string) *PointsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PointsCreate) SetNillableDescription(v *string) *PointsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PointsCreate) SetUserID(id int) *PointsCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PointsCreate) SetUser(v *User) *PointsCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PointsMutation object of the builder.
func (_c *PointsCreate) Mutation() *PointsMutation {
	return _c.mutation
}

// Save creates the Points in the database.
func (_c *PointsCreate) Save(ctx context.Context) (*Points, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PointsCreate) SaveX(ctx context.Context) *Points {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PointsCreate) defaults() {
	if _, ok := _c.mutation.Points(); !ok {
		v := points.DefaultPoints
		_c.mutation.SetPoints(v)
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		v := points.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PointsCreate) check() error {
	if _, ok := _c.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "Points.points"`)}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "Points.granted_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Points.user"`)}
	}
	return nil
}

func (_c *PointsCreate) sqlSave(ctx context.Context) (*Points, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PointsCreate) createSpec() (*Points, *sqlgraph.CreateSpec) {
	var (
		_node = &Points{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(points.Table, sqlgraph.NewFieldSpec(points.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Points(); ok {
		_spec.SetField(points.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(points.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(points.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   points.UserTable,
			Columns: []string{points.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_points = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PointsCreateBulk is the builder for creating many Points entities in bulk.
type PointsCreateBulk struct {
	config
	err      error
	builders []*PointsCreate
}

// Save creates the Points entities in the database.
func (_c *PointsCreateBulk) Save(ctx context.Context) ([]*Points, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Points, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PointsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PointsCreateBulk) SaveX(ctx context.Context) []*Points {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
