// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/predicate"
	"github.com/database-playground/backend-v2/ent/scopeset"
)

// ScopeSetQuery is the builder for querying ScopeSet entities.
type ScopeSetQuery struct {
	config
	ctx        *QueryContext
	order      []scopeset.OrderOption
	inters     []Interceptor
	predicates []predicate.ScopeSet
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*ScopeSet) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScopeSetQuery builder.
func (ssq *ScopeSetQuery) Where(ps ...predicate.ScopeSet) *ScopeSetQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *ScopeSetQuery) Limit(limit int) *ScopeSetQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *ScopeSetQuery) Offset(offset int) *ScopeSetQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *ScopeSetQuery) Unique(unique bool) *ScopeSetQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *ScopeSetQuery) Order(o ...scopeset.OrderOption) *ScopeSetQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// First returns the first ScopeSet entity from the query.
// Returns a *NotFoundError when no ScopeSet was found.
func (ssq *ScopeSetQuery) First(ctx context.Context) (*ScopeSet, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scopeset.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *ScopeSetQuery) FirstX(ctx context.Context) *ScopeSet {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScopeSet ID from the query.
// Returns a *NotFoundError when no ScopeSet ID was found.
func (ssq *ScopeSetQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scopeset.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *ScopeSetQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScopeSet entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScopeSet entity is found.
// Returns a *NotFoundError when no ScopeSet entities are found.
func (ssq *ScopeSetQuery) Only(ctx context.Context) (*ScopeSet, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scopeset.Label}
	default:
		return nil, &NotSingularError{scopeset.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *ScopeSetQuery) OnlyX(ctx context.Context) *ScopeSet {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScopeSet ID in the query.
// Returns a *NotSingularError when more than one ScopeSet ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *ScopeSetQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scopeset.Label}
	default:
		err = &NotSingularError{scopeset.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *ScopeSetQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScopeSets.
func (ssq *ScopeSetQuery) All(ctx context.Context) ([]*ScopeSet, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryAll)
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScopeSet, *ScopeSetQuery]()
	return withInterceptors[[]*ScopeSet](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *ScopeSetQuery) AllX(ctx context.Context) []*ScopeSet {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScopeSet IDs.
func (ssq *ScopeSetQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryIDs)
	if err = ssq.Select(scopeset.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *ScopeSetQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *ScopeSetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryCount)
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*ScopeSetQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *ScopeSetQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *ScopeSetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryExist)
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *ScopeSetQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScopeSetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *ScopeSetQuery) Clone() *ScopeSetQuery {
	if ssq == nil {
		return nil
	}
	return &ScopeSetQuery{
		config:     ssq.config,
		ctx:        ssq.ctx.Clone(),
		order:      append([]scopeset.OrderOption{}, ssq.order...),
		inters:     append([]Interceptor{}, ssq.inters...),
		predicates: append([]predicate.ScopeSet{}, ssq.predicates...),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScopeSet.Query().
//		GroupBy(scopeset.FieldSlug).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *ScopeSetQuery) GroupBy(field string, fields ...string) *ScopeSetGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScopeSetGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = scopeset.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//	}
//
//	client.ScopeSet.Query().
//		Select(scopeset.FieldSlug).
//		Scan(ctx, &v)
func (ssq *ScopeSetQuery) Select(fields ...string) *ScopeSetSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &ScopeSetSelect{ScopeSetQuery: ssq}
	sbuild.label = scopeset.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScopeSetSelect configured with the given aggregations.
func (ssq *ScopeSetQuery) Aggregate(fns ...AggregateFunc) *ScopeSetSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *ScopeSetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !scopeset.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *ScopeSetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScopeSet, error) {
	var (
		nodes   = []*ScopeSet{}
		withFKs = ssq.withFKs
		_spec   = ssq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, scopeset.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScopeSet).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScopeSet{config: ssq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ssq.modifiers) > 0 {
		_spec.Modifiers = ssq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range ssq.loadTotal {
		if err := ssq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *ScopeSetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	if len(ssq.modifiers) > 0 {
		_spec.Modifiers = ssq.modifiers
	}
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *ScopeSetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scopeset.Table, scopeset.Columns, sqlgraph.NewFieldSpec(scopeset.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scopeset.FieldID)
		for i := range fields {
			if fields[i] != scopeset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *ScopeSetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(scopeset.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = scopeset.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScopeSetGroupBy is the group-by builder for ScopeSet entities.
type ScopeSetGroupBy struct {
	selector
	build *ScopeSetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *ScopeSetGroupBy) Aggregate(fns ...AggregateFunc) *ScopeSetGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *ScopeSetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, ent.OpQueryGroupBy)
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScopeSetQuery, *ScopeSetGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *ScopeSetGroupBy) sqlScan(ctx context.Context, root *ScopeSetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScopeSetSelect is the builder for selecting fields of ScopeSet entities.
type ScopeSetSelect struct {
	*ScopeSetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *ScopeSetSelect) Aggregate(fns ...AggregateFunc) *ScopeSetSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *ScopeSetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, ent.OpQuerySelect)
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScopeSetQuery, *ScopeSetSelect](ctx, sss.ScopeSetQuery, sss, sss.inters, v)
}

func (sss *ScopeSetSelect) sqlScan(ctx context.Context, root *ScopeSetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
