// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/group"
	"github.com/database-playground/backend-v2/ent/scopeset"
)

// ScopeSetCreate is the builder for creating a ScopeSet entity.
type ScopeSetCreate struct {
	config
	mutation *ScopeSetMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *ScopeSetCreate) SetSlug(v string) *ScopeSetCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScopeSetCreate) SetDescription(v string) *ScopeSetCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScopeSetCreate) SetNillableDescription(v *string) *ScopeSetCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *ScopeSetCreate) SetScopes(v []string) *ScopeSetCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *ScopeSetCreate) AddGroupIDs(ids ...int) *ScopeSetCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *ScopeSetCreate) AddGroups(v ...*Group) *ScopeSetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// Mutation returns the ScopeSetMutation object of the builder.
func (_c *ScopeSetCreate) Mutation() *ScopeSetMutation {
	return _c.mutation
}

// Save creates the ScopeSet in the database.
func (_c *ScopeSetCreate) Save(ctx context.Context) (*ScopeSet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScopeSetCreate) SaveX(ctx context.Context) *ScopeSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScopeSetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScopeSetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScopeSetCreate) defaults() {
	if _, ok := _c.mutation.Scopes(); !ok {
		v := scopeset.DefaultScopes
		_c.mutation.SetScopes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScopeSetCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "ScopeSet.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := scopeset.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ScopeSet.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "ScopeSet.scopes"`)}
	}
	return nil
}

func (_c *ScopeSetCreate) sqlSave(ctx context.Context) (*ScopeSet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScopeSetCreate) createSpec() (*ScopeSet, *sqlgraph.CreateSpec) {
	var (
		_node = &ScopeSet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scopeset.Table, sqlgraph.NewFieldSpec(scopeset.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(scopeset.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(scopeset.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(scopeset.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   scopeset.GroupsTable,
			Columns: scopeset.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScopeSetCreateBulk is the builder for creating many ScopeSet entities in bulk.
type ScopeSetCreateBulk struct {
	config
	err      error
	builders []*ScopeSetCreate
}

// Save creates the ScopeSet entities in the database.
func (_c *ScopeSetCreateBulk) Save(ctx context.Context) ([]*ScopeSet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScopeSet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScopeSetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScopeSetCreateBulk) SaveX(ctx context.Context) []*ScopeSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScopeSetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScopeSetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
