// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database-playground/backend-v2/ent/question"
	"github.com/database-playground/backend-v2/ent/submission"
	"github.com/database-playground/backend-v2/ent/user"
	"github.com/database-playground/backend-v2/models"
)

// SubmissionCreate is the builder for creating a Submission entity.
type SubmissionCreate struct {
	config
	mutation *SubmissionMutation
	hooks    []Hook
}

// SetSubmittedCode sets the "submitted_code" field.
func (_c *SubmissionCreate) SetSubmittedCode(v string) *SubmissionCreate {
	_c.mutation.SetSubmittedCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubmissionCreate) SetStatus(v submission.Status) *SubmissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *SubmissionCreate) SetResult(v models.SubmissionResult) *SubmissionCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *SubmissionCreate) SetSubmittedAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableSubmittedAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_c *SubmissionCreate) SetQuestionID(id int) *SubmissionCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetQuestion sets the "question" edge to the Question entity.
func (_c *SubmissionCreate) SetQuestion(v *Question) *SubmissionCreate {
	return _c.SetQuestionID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *SubmissionCreate) SetUserID(id int) *SubmissionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubmissionCreate) SetUser(v *User) *SubmissionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_c *SubmissionCreate) Mutation() *SubmissionMutation {
	return _c.mutation
}

// Save creates the Submission in the database.
func (_c *SubmissionCreate) Save(ctx context.Context) (*Submission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubmissionCreate) SaveX(ctx context.Context) *Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubmissionCreate) defaults() {
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		v := submission.DefaultSubmittedAt()
		_c.mutation.SetSubmittedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubmissionCreate) check() error {
	if _, ok := _c.mutation.SubmittedCode(); !ok {
		return &ValidationError{Name: "submitted_code", err: errors.New(`ent: missing required field "Submission.submitted_code"`)}
	}
	if v, ok := _c.mutation.SubmittedCode(); ok {
		if err := submission.SubmittedCodeValidator(v); err != nil {
			return &ValidationError{Name: "submitted_code", err: fmt.Errorf(`ent: validator failed for field "Submission.submitted_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Submission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "Submission.result"`)}
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		return &ValidationError{Name: "submitted_at", err: errors.New(`ent: missing required field "Submission.submitted_at"`)}
	}
	if len(_c.mutation.QuestionIDs()) == 0 {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required edge "Submission.question"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Submission.user"`)}
	}
	return nil
}

func (_c *SubmissionCreate) sqlSave(ctx context.Context) (*Submission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubmissionCreate) createSpec() (*Submission, *sqlgraph.CreateSpec) {
	var (
		_node = &Submission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(submission.Table, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SubmittedCode(); ok {
		_spec.SetField(submission.FieldSubmittedCode, field.TypeString, value)
		_node.SubmittedCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(submission.FieldResult, field.TypeJSON, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(submission.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = value
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.QuestionTable,
			Columns: []string{submission.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.question_submissions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.UserTable,
			Columns: []string{submission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_submissions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubmissionCreateBulk is the builder for creating many Submission entities in bulk.
type SubmissionCreateBulk struct {
	config
	err      error
	builders []*SubmissionCreate
}

// Save creates the Submission entities in the database.
func (_c *SubmissionCreateBulk) Save(ctx context.Context) ([]*Submission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Submission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubmissionCreateBulk) SaveX(ctx context.Context) []*Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
