// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Database is the predicate function for database builders.
type Database func(*sql.Selector)

// Events is the predicate function for events builders.
type Events func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Points is the predicate function for points builders.
type Points func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// ScopeSet is the predicate function for scopeset builders.
type ScopeSet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
